name: Render Deploy

on:
  push:
    branches:
      - main # 必要に応じて変更

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug API Key and Service ID
        run: |
          echo "API Key: ${{ secrets.RENDER_API_KEY }}"
          echo "Service ID: ${{ secrets.RENDER_SERVICE_ID }}"

      - name: Trigger Render Deployment
        uses: ttskch/render-deploy@latest
        with:
          api-key: ${{ secrets.RENDER_API_KEY }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          interval: 120  # 2分間隔
          timeout: 900   # 15分タイムアウト
